# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /ihp/departments/D-SYA/work/miglioranza/Transmitter_repo/Transmitter/Transmitter.srcs/sources_1/bd/Design_2/ip/Design_2_CU_top_0_1/Design_2_CU_top_0_1.xci
# IP: The module: 'Design_2_CU_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /ihp/departments/D-SYA/work/miglioranza/Transmitter_repo/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_CU_top_0_1/sources_1/ip/tx_data_fifo/tx_data_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tx_data_fifo || ORIG_REF_NAME==tx_data_fifo} -quiet] -quiet

# XDC: /ihp/departments/D-SYA/work/miglioranza/Transmitter_repo/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_CU_top_0_1/constrs_1/new/CU_constraint.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_2_CU_top_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /ihp/departments/D-SYA/work/miglioranza/Transmitter_repo/Transmitter/Transmitter.srcs/sources_1/bd/Design_2/ip/Design_2_CU_top_0_1/Design_2_CU_top_0_1.xci
# IP: The module: 'Design_2_CU_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /ihp/departments/D-SYA/work/miglioranza/Transmitter_repo/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_CU_top_0_1/sources_1/ip/tx_data_fifo/tx_data_fifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tx_data_fifo || ORIG_REF_NAME==tx_data_fifo} -quiet] -quiet

# XDC: /ihp/departments/D-SYA/work/miglioranza/Transmitter_repo/Transmitter/Transmitter.gen/sources_1/bd/Design_2/ip/Design_2_CU_top_0_1/constrs_1/new/CU_constraint.xdc
# XDC: The top module name and the constraint reference have the same name: 'Design_2_CU_top_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
